# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad501e5221a542579c22b9af997ef7a181d3dcdaedb3dc3046735b7a1094e1afee2e44135911eab83b969f3aa9d44cf077e0536d4212ed53358e2f972832747d

test:
  secret_key_base: 9086671bf2584a9b61eb17f01bfe0eb9ba3f4ee6b8e119b79a4b658460a82f7777d66adc5e865bed44604e49e9a46932c8e89155cbb0058b06b207ea4ca4a70e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
